### ISSUE TITLE
'DiffMatchPatch'  initializer error

### ISSUE THREAD

**Issue by hamedaakhlaghi** [klassen-software-solutions/KSSDiff#10]
When I want to use 'DiffMatchPatch' there was an error about the constructor of it:
 'DiffMatchPatch'  initializer is inaccessible due to 'internal' protection level.
 How can I use the package, I read the test and I need to use  this method:
  let dmp = DiffMatchPatch() //  the error is here
 var diffs = dmp.main("hello word", "hello")

**Comment by stevenklassen8376** [comment]
Hmm, you have found an error. There are supposed to be two ways to call this code. The simplest is to call the string extension `differencesFrom`. The second is to call `DiffMatchPatch.main` but as you note you can't do that since you can't create the object.

I will tag this as a bug and see if I can get it fixed in the next week.

**Comment by hamedaakhlaghi** [comment]
The result of `differencesFrom` seems wrong for example:
```swift
        let s = "Hi Hamed"
        let s2 = "How are you"
        let diff = s.differencesFrom(s2)
        print(diff)
``` 

`
[KSSDiff.Difference(inOriginal: Optional("ow"), inNew: nil),
KSSDiff.Difference(inOriginal: nil, inNew: Optional("i")), 
KSSDiff.Difference(inOriginal: nil, inNew: Optional("H")),
KSSDiff.Difference(inOriginal: Optional("r"), inNew: nil),
KSSDiff.Difference(inOriginal: nil, inNew: Optional("m")), 
KSSDiff.Difference(inOriginal: Optional(" you"), inNew: nil), 
KSSDiff.Difference(inOriginal: nil, inNew: Optional("d"))]
`

**Comment by stevenklassen8376** [comment]
This looks correct to me. It is saying that the move from "How are you" to "Hi Hamed" has done the following:

1. Removed "ow" (result: "Hi Hamed" --> "H are you")
2. Added "hi" (result: "Hi are you")
3. Added "H" (result: "Hi Hare you")
4. Removed "r" (result: "Hi Hae you")
5. Added "m" (result: "Hi Hame you")
6. Removed " you" (result: "Hi Hame")
7. Added "d" (result: "Hi Hamed")

**Comment by hamedaakhlaghi** [comment]
I think based on your tests with using `DiffMatchPatch.main` the result should be something like this:
1. Remove "Hi Hamed"
2. Add "How are you"

And for `let s = "Hi Hamed"`, ` let s2 = "Hello Hamed"` should be like this:
1. Remove "Hi"
2.  Add  "Hello"
3. Equal "Hamed"

**Comment by stevenklassen8376** [comment]
The algorithm tries to keep as much common as possible. For example remove "Hi Hamed" and add "How are you" would absolutely not be correct, because it could at the very least be remove "i Hamed" and add "ow are you", keeping the initial "H" in place. But in any event, the snippet you provided was going the other way, it was saying essentially what are the differences required to change "How are you" to "Hi Hamed", not the other way around. I.e. The string you are calling it on is the new string and the one you pass in is the original.

Your second case I would hope that `"Hello Hamed".differencesFrom("Hi Hamed")` would result in the following steps (I have not added this test case to see)...

1. Remove "i" (result: "H Hamed")
2. Add "ello" (result: "Hello Hamed")
